
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Camilo
 */
public class VenTabla extends javax.swing.JFrame {

    /**
     * Creates new form VenTabla
     */
    public VenTabla() {
        initComponents();
        this.setTitle("Fergus Tabla");
        setLocationRelativeTo(null);
        cargarTabla();
        apagar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Actualizar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaComponentes = new javax.swing.JTable();
        Ocultar = new javax.swing.JButton();
        Mostrar = new javax.swing.JButton();
        Id = new javax.swing.JTextField();
        Fabricante = new javax.swing.JTextField();
        Modelo = new javax.swing.JTextField();
        Ensamblador = new javax.swing.JTextField();
        Cantidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Procesador = new javax.swing.JRadioButton();
        TarjetaDeVideo = new javax.swing.JRadioButton();
        Buscar = new javax.swing.JButton();
        CampoBuscar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        TablaComponentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id de registro", "Fabricante", "Modelo", "Ensamblador", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(TablaComponentes);

        Ocultar.setText("Ocultar");
        Ocultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OcultarActionPerformed(evt);
            }
        });

        Mostrar.setText("Mostrar Datos");
        Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActionPerformed(evt);
            }
        });

        Id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IdKeyTyped(evt);
            }
        });

        Fabricante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FabricanteKeyTyped(evt);
            }
        });

        Ensamblador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EnsambladorKeyTyped(evt);
            }
        });

        Cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CantidadKeyTyped(evt);
            }
        });

        jLabel1.setText("Id");

        jLabel2.setText("Fabricante");

        jLabel3.setText("Modelo");

        jLabel4.setText("Ensamblador");

        jLabel5.setText("Cantidad");

        buttonGroup1.add(Procesador);
        Procesador.setText("Procesador");
        Procesador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcesadorActionPerformed(evt);
            }
        });

        buttonGroup1.add(TarjetaDeVideo);
        TarjetaDeVideo.setText("Tarjeta de video");
        TarjetaDeVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarjetaDeVideoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(Mostrar)
                .addGap(236, 236, 236)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Actualizar)
                    .addComponent(Ocultar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Eliminar)
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 995, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel1)
                .addGap(173, 173, 173)
                .addComponent(jLabel2)
                .addGap(142, 142, 142)
                .addComponent(jLabel3)
                .addGap(140, 140, 140)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(85, 85, 85))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Procesador, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(Ensamblador, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TarjetaDeVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ensamblador, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Procesador)
                    .addComponent(TarjetaDeVideo))
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Actualizar)
                    .addComponent(Eliminar)
                    .addComponent(Mostrar))
                .addGap(75, 75, 75)
                .addComponent(Ocultar)
                .addGap(37, 37, 37))
        );

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        jLabel6.setText("Id a buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CampoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(CampoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(Buscar)
                        .addGap(396, 396, 396))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OcultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OcultarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_OcultarActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        ResultSet rs = null;
        Connection conexion = getConexion();

        try {
            PreparedStatement ps = (PreparedStatement) conexion.prepareStatement("update productos set Fabricante='"
                    + Fabricante.getText() + "', Modelo='" + Modelo.getText() + "', Ensamblador='" + Ensamblador.getText()
                    + "', Cantidad='" + Cantidad.getText() + "' where IdRegistro='" + Id.getText() + "'");

            int result = ps.executeUpdate();

            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Registro modificado de manera exitosa");
                cargarTabla();
                limpiar();

            } else {
                JOptionPane.showMessageDialog(null, "Registro no modificado");
            }

            conexion.close();

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, "Error " + ex);
        }
    }//GEN-LAST:event_ActualizarActionPerformed

    private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed
        cargarTabla();
    }//GEN-LAST:event_MostrarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed

        Connection conexion;
        PreparedStatement ps;

        try {

            conexion = getConexion();
            ps = (PreparedStatement) conexion.prepareStatement("DELETE FROM productos WHERE idRegistro=?");
            ps.setString(1, JOptionPane.showInputDialog("Ingrese el numero de registro a eliminar"));

            int result = ps.executeUpdate();

            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Registro eliminado de manera exitosa");
                cargarTabla();
            } else {
                JOptionPane.showMessageDialog(null, "Registro no eliminado");
            }

            conexion.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex);
        }

    }//GEN-LAST:event_EliminarActionPerformed

    private void IdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdKeyTyped
        char valido = evt.getKeyChar();

        if (Character.isLetter(valido)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_IdKeyTyped

    private void FabricanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FabricanteKeyTyped
        char valido = evt.getKeyChar();

        if (Character.isDigit(valido)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo letras");
        }
    }//GEN-LAST:event_FabricanteKeyTyped

    private void EnsambladorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EnsambladorKeyTyped
        char valido = evt.getKeyChar();

        if (Character.isDigit(valido)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo letras");
        }
    }//GEN-LAST:event_EnsambladorKeyTyped

    private void CantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantidadKeyTyped
        char valido = evt.getKeyChar();

        if (Character.isLetter(valido)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_CantidadKeyTyped

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        String query = "";
        query = "SELECT* FROM productos WHERE IdRegistro=" + CampoBuscar.getText();
        DefaultTableModel modeloTabla = new DefaultTableModel();
        TablaComponentes.setModel(modeloTabla);

        modeloTabla.addColumn("IdRegistro");
        modeloTabla.addColumn("Fabricante");
        modeloTabla.addColumn("Modelo");
        modeloTabla.addColumn("Ensamblador");
        modeloTabla.addColumn("Cantidad");

        PreparedStatement ps;
        ResultSet rs;

        try {
            Connection con = getConexion();

            ps = (PreparedStatement) con.prepareStatement(query);
            rs = ps.executeQuery();

            while (rs.next()) {

                Id.setEnabled(false);
                Id.setText(rs.getString("IdRegistro"));
                Fabricante.setText(rs.getString("Fabricante"));
                Modelo.setText(rs.getString("Modelo"));
                Ensamblador.setText(rs.getString("Ensamblador"));
                Cantidad.setText(rs.getString("Cantidad"));
                Actualizar.setEnabled(true);
                activar();

                Object fila[] = new Object[5];
                for (int i = 0; i < 5; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modeloTabla.addRow(fila);
            }

        } catch (SQLException e) {
            System.err.println("Error " + e);
        }

    }//GEN-LAST:event_BuscarActionPerformed

    private void ProcesadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcesadorActionPerformed
        if (Procesador.isSelected()) {
            Ensamblador.setEnabled(false);
            Fabricante.setEnabled(true);
            Modelo.setEnabled(true);
            Id.setEnabled(false);
            Cantidad.setEnabled(true);
            Ensamblador.setText("");
        }
    }//GEN-LAST:event_ProcesadorActionPerformed

    private void TarjetaDeVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarjetaDeVideoActionPerformed
        if (TarjetaDeVideo.isSelected()) {
            Ensamblador.setEnabled(true);
            Fabricante.setEnabled(true);
            Modelo.setEnabled(true);
            Id.setEnabled(false);
            Cantidad.setEnabled(true);
        }
    }//GEN-LAST:event_TarjetaDeVideoActionPerformed

    /**
     * @param args the command line arguments
     */
    public void cargarTabla() {

        DefaultTableModel modeloTabla = new DefaultTableModel();
        TablaComponentes.setModel(modeloTabla);

        modeloTabla.addColumn("Id Registro");
        modeloTabla.addColumn("Fabricante");
        modeloTabla.addColumn("Modelo");
        modeloTabla.addColumn("Ensamblador");
        modeloTabla.addColumn("Cantidad");

        PreparedStatement ps;
        ResultSet rs;

        try {
            Connection con = getConexion();

            ps = (PreparedStatement) con.prepareStatement("SELECT* FROM productos");
            rs = ps.executeQuery();

            while (rs.next()) {

                Object fila[] = new Object[5];
                for (int i = 0; i < 5; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modeloTabla.addRow(fila);
            }

        } catch (SQLException e) {
            System.err.println("Error " + e);
        }

    }

    public void limpiar() {
        Ensamblador.setText("");
        Fabricante.setText("");
        Id.setText("");
        Modelo.setText("");
        Cantidad.setText("");
    }

    public void apagar() {
        Ensamblador.setEnabled(false);
        Fabricante.setEnabled(false);
        Modelo.setEnabled(false);
        Id.setEnabled(false);
        Cantidad.setEnabled(false);
        Actualizar.setEnabled(false);
    }
    
    public void activar() {
        Ensamblador.setEnabled(true);
        Fabricante.setEnabled(true);
        Modelo.setEnabled(true);
        Id.setEnabled(false);
        Cantidad.setEnabled(true);
        Actualizar.setEnabled(true);
    }

    private final String dataBase = "electronica";
    private final String user = "Fergus";
    private final String password = "123456";
    private final String URL = "jdbc:mysql://localhost:3306/" + dataBase + "?autoReconnect=true&useSSL=false";

    private Connection con = null;

    public Connection getConexion() {

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(URL, user, password);

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "Error " + ex);

        }

        return con;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VenTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VenTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VenTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VenTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VenTabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton Buscar;
    private javax.swing.JTextField CampoBuscar;
    private javax.swing.JTextField Cantidad;
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextField Ensamblador;
    private javax.swing.JTextField Fabricante;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField Modelo;
    private javax.swing.JButton Mostrar;
    private javax.swing.JButton Ocultar;
    private javax.swing.JRadioButton Procesador;
    private javax.swing.JTable TablaComponentes;
    private javax.swing.JRadioButton TarjetaDeVideo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
